### ISSUE TITLE
about codalab error

### ISSUE THREAD

**Issue by zhangxiaoxiao-tech** [houzhijian/CONQUER#4]
When I follow the example to submit my zip of json to codalab, it gives me an error:

Traceback (most recent call last):
File "/worker/worker.py", line 323, in run
bundles = get_bundle(root_dir, 'run', bundle_url)
File "/worker/worker.py", line 180, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 180, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 171, in get_bundle
metadata = yaml.load(mf)
File "/usr/local/lib/python2.7/dist-packages/yaml/init.py", line 69, in load
loader = Loader(stream)
File "/usr/local/lib/python2.7/dist-packages/yaml/loader.py", line 34, in init
Reader.init(self, stream)
File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 85, in init
self.determine_encoding()
File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 135, in determine_encoding
self.update(1)
File "/usr/local/lib/python2.7/dist-packages/yaml/reader.py", line 165, in update
exc.encoding, exc.reason)
ReaderError: 'utf8' codec can't decode byte #xaf: invalid start byte
in "/tmp/codalab/tmpOjOaDx/run/input/res/metadata", position 11

How can I fix the error?

**Comment by houzhijian** [comment]
Hi,
     
Thanks for your interest in this work, CONQUER.

Based on your given information, the problem seems to be related to the format of your JSON file. But I am sorry that I also don't know the exact solution.

Please refer to the page "https://github.com/jayleicn/TVRetrieval/blob/master/standalone_eval/README.md" and cross-check the provided sample and your JSON file.

I hope this reply is helpful to you.
